export const routesConfig = {
  home: "/",
  auth: {
    base: "/auth",
    login: "/auth/login",
    requestPasswordReset: "/auth/request-password-reset",
    resetPassword: "/auth/reset-password/:resetToken",
  },
  app: {
    dashboard: "/",
    stockIn: "/stock-in",
    createStockIn: "/stock-in/create",
    stockInDetail: "/stock-in/:id",
    stockOut: "/stock-out",
    createStockOut: "/stock-out/create",
    stockOutDetail: "/stock-out/:id",
    purchaseRequests: "/purchase-requests",
    createPurchaseRequest: "/purchase-requests/create",
    editPurchaseRequest: "/purchase-requests/:id/edit",
    purchaseRequestDetail: "/purchase-requests/:id",
    goodsReceipts: "/goods-receipts",
    createGoodsReceipt: "/goods-receipts/create",
    editGoodsReceipt: "/goods-receipts/:id/edit",
    goodsReceiptDetail: "/goods-receipts/:id",
    categories: "/categories",
    products: "/products",
    stockSummary: "/stock-summary",
    users: "/users",
    settings: "/settings",
  },
} as const;

